name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 确保完整克隆仓库

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23  # 修改为你的 Go 版本

    - name: Move to src directory
      run: cd src  # 确保在 src 目录执行

    - name: Verify go.mod exists
      run: ls -l src/go.mod || echo "go.mod not found!"  # 检查 go.mod

    - name: Install dependencies
      run: cd src && go mod tidy  # 进入 src 目录并下载依赖

    - name: Run tests
      run: cd src && go test -v ./...  # 进入 src 目录并运行测试
